name: Pipeline
on: push
jobs:
  lint:
    name: Lint with PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@1.6.0
        with:
          php-version: 7.4
          extensions: mbstring
          coverage: none
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Lint with PHP_CodeSniffer
        run: vendor/bin/phpcs
  test:
    name: Test with PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@1.6.0
        with:
          php-version: 7.4
          extensions: mbstring
          coverage: pcov
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Test with PHPUnit
        run: |
          mkdir -p artifacts/
          vendor/bin/phpunit \
            --log-junit=artifacts/phpunit-junit.xml \
            --coverage-clover=artifacts/phpunit-coverage.xml \
            --coverage-text
      - name: Upload coverage reports
        uses: actions/upload-artifact@v1.0.0
        with:
          name: coverage-reports
          path: artifacts
  analyse:
    name: Analyse with Sonar Scanner
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract git context
        id: git
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Download coverage reports
        uses: actions/download-artifact@v1.0.0
        with:
          name: coverage-reports
          path: artifacts
      - name: Setup sonar.properties
        run: |
          # Setup version
          VERSION=$(jq -r .version composer.json)
          echo "sonar.projectVersion=${VERSION}" >> sonar-project.properties

          # Setup branches
          echo "sonar.branch.name=${{ steps.git.outputs.branch }}" >> sonar-project.properties

          if [[ "${{ steps.git.outputs.branch }}" = "dev" ]]; then
            echo "sonar.branch.target=master" >> sonar-project.properties
            PARENT_BRANCH="master"
          elif [[ "${{ steps.git.outputs.branch }}" != "master" ]]; then
            echo "sonar.branch.target=dev" >> sonar-project.properties
            PARENT_BRANCH="dev"
          fi
      - name: Analyse with Sonar Scanner
        uses: mathrix-education/sonar-scanner@master
        with:
          version: 4.2.0.1873 # required
          typescript: false
          scan: true
          args: -Dsonar.login=${{ secrets.SONAR_TOKEN }}
